apiVersion: apps/v1
kind: Deployment
metadata:
  name: memex-ui
spec:
  template:
    spec:
      containers:
      - name: memex-ui
        image: memex-ui:0.0.1
        ports:
        - containerPort: 80
          hostPort: 8088
