apiVersion: v1
kind: Service
metadata:
  name: memex-ui
  labels:
    component: memex-ui
spec:
  ports:
    - port: 8088
      targetPort: 80
  clusterIP: None
  selector:
    component: memex-ui

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memex-ui
spec:
  selector:
    matchLabels:
      component: memex-ui
  serviceName: memex-ui
  template:
    metadata:
      labels:
        component: memex-ui
    spec:
      containers:
        - name: memex-ui
          image: memex-ui:0.0.1
          ports:
            - hostPort: 8088
              containerPort: 80
